
const spots=[
    {"space_number":"Spot 1","id":"1","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 2","id":"2","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 3","id":"3","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 4","id":"4","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 5","id":"5","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 6","id":"6","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 7","id":"7","isOccupied":true, 'isSelected': false},
    {"space_number":"Spot 8","id":"8","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 9","id":"9","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 10","id":"10","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 11","id":"11","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 12","id":"12","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 13","id":"13","isOccupied":true, 'isSelected': false},
    {"space_number":"Spot 14","id":"14","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 15","id":"15","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 16","id":"16","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 17","id":"17","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 18","id":"18","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 19","id":"19","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 20","id":"20","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 21","id":"21","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 22","id":"22","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 23","id":"23","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 24","id":"24","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 25","id":"25","isOccupied":false, 'isSelected': true},
    {"space_number":"Spot 26","id":"26","isOccupied":true, 'isSelected': false},
    {"space_number":"Spot 27","id":"27","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 28","id":"28","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 29","id":"29","isOccupied":false, 'isSelected': false},
    {"space_number":"Spot 30","id":"30","isOccupied":false, 'isSelected': false}
];

export default spots;